### ISSUE TITLE
Feature enhancement in Shiny App - Expression Level Plot

### ISSUE THREAD

**Issue by ShrutiMarwaha** [JinmiaoChenLab/cytofkit#13]
Hi Jinmiao,

When comparing two conditions, ‘cluster plot’ under ‘cluster panel’ allows to separate plots by samples; this is very useful for visual comparison and EDA. However, under ‘marker panel’, ‘expression level plot’ generates a separate plot for each sample where the scale (on right in legend) is limited to that particular sample. A different scale for two conditions, makes it challenging to compare the change in expression levels of the same marker in the two conditions. It will be helpful, if shiny app or within R code, one can calculate min and max for a given marker from the specified conditions and then use same scale to generate the two different plots. 

Best,
Shruti

**Comment by MattMyint** [comment]
Hi Shruti,

We've updated the code on the development branch to have consistent scaling of marker expression levels across samples

Let me know if there's any issues with the update!

**Comment by ShrutiMarwaha** [comment]
Thanks Matthew. It works!

**Comment by SamGG** [comment]
Hi Matt,
Could you put a pointer to the changes associated with this new feature?
Cheers.

**Comment by MattMyint** [comment]
Hi,

Sorry, to clarify, you want me to reference the commit that introduced this new feature?

**Comment by SamGG** [comment]
Yes. If it is no more than a few minutes, could you tell me the commit code that refers to those changes. But feel free.

**Comment by MattMyint** [comment]
Sorry for the delay, the commit was a577008725a9d86dd3d52ad4e9597508edadaa94, and 7c70f874307e138608b7ad0d9950ed24a0fd94da also updated the default behaviour

**Comment by SamGG** [comment]
Thanks.
