### ISSUE TITLE
Bug in cytofkit() fcsFiles parameter

### ISSUE THREAD

**Issue by esimonds** [JinmiaoChenLab/cytofkit#19]
When running without the GUI using the cytofkit() function, I frequently get this error:

```
> cytofkit(fcsFiles = ".",
+            markers = clustermarkers,
+            projectName = outdir,
+            transformMethod = "cytofAsinh",
+            mergeMethod = "ceil",
+            fixedNum = 3000,  ## reduce this number for testing
+            dimReductionMethod = "pca",
+            clusterMethods = "Rphenograph",
+            visualizationMethods = "tsne",
+            progressionMethod = NULL,
+            resultDir = getwd(),
+            saveResults = TRUE,
+            saveObject = TRUE)
Error in setwd(rawFCSdir) : cannot change working directory
```

The only workaround seems to be to run the following code before the function above.
```
setwd(fcsdir)
fcsfiles <- list.files(".", pattern=".fcs")
```
  
This appears to be due to lines 152-163 of cytofkit.R:

```
    if (is.null(fcsFiles) || is.na(fcsFiles) || is.nan(fcsFiles)){
        stop("Wrong input fcsFiles!")
    }else if (length(fcsFiles) == 1 && file.info(fcsFiles)$isdir) {
        fcsFiles <- list.files(path = fcsFiles, pattern = ".fcs$", 
            full.names = TRUE)
        rawFCSdir <- fcsFiles
    }else{
        if(dirname(fcsFiles[1]) == "."){
            rawFCSdir <- getwd()
        }else{
            rawFCSdir <- dirname(fcsFiles[1])  
        }
    }
    setwd(rawFCSdir)
```

The way the code is currently written, if the parameter fcsFiles is set to a valid folder, then the variable "rawFCSdir" will be rewritten with a vector of the FCS filenames within that folder. At line 163, it attempts to set the working directory to the filenames, resulting in an error. 

I'm sure some fiddling with lines 150-163 can produce the desired error checking behavior and allow the function to proceed when a valid folder name is entered.

- Erin

**Comment by MattMyint** [comment]
After debugging, I found the problem occurs in this chunk
```
}else if (length(fcsFiles) == 1 && file.info(fcsFiles)$isdir) {
        fcsFiles <- list.files(path = fcsFiles, pattern = ".fcs$", 
            full.names = TRUE)
        rawFCSdir <- fcsFiles    ### problematic line
```
I'm changing the problematic line to `rawFCSdir <- dirname(fcsFiles)` to fix the behaviour

**Comment by MattMyint** [comment]
If the issue persists in another manner, feel free to re-open this issue
