### ISSUE TITLE
FlowSOM is not showing up when cytofkit_GUI() is run

### ISSUE THREAD

**Issue by Thatstatue** [JinmiaoChenLab/cytofkit#24]
![image](https://user-images.githubusercontent.com/1736071/34910399-56a908b6-f882-11e7-9551-b22a0f21ac20.png)
I have installed FlowSOM separately yet it does not appear in the GUI. Is this a bug or an issue on my end?

**Comment by MattMyint** [comment]
Hi,

Could you check your version using `packageVersion("cytofkit")`?

I suspect you're using an previous version of cytofkit that doesn't have FlowSOM as an option on the GUI.

**Comment by Thatstatue** [comment]
I have version 1.10.0.

**Comment by MattMyint** [comment]
Ah, unfortunately, this feature was only added in after the release version 1.10.0 came out.

You would need to install the devel version here to be able to specify FlowSOM in the GUI.

**Comment by Thatstatue** [comment]
That seems to have fixed it. Thanks.
