### ISSUE TITLE
Why I cannot get "library ("cytofkit")"

### ISSUE THREAD

**Issue by liyan99** [JinmiaoChenLab/cytofkit#3]
When I want to get  "library ("cytofkit")"
it showed below, can anyone help me with this? Thanks a lot.
> biocLite("cytofkit")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.4 (BiocInstaller 1.24.0), R 3.3.1 (2016-06-21).
Installing package(s) ‘cytofkit’
trying URL 'https://bioconductor.org/packages/3.4/bioc/bin/windows/contrib/3.3/cytofkit_1.6.1.zip'
Content type 'application/zip' length 9427861 bytes (9.0 MB)
downloaded 9.0 MB

package ‘cytofkit’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\li99\AppData\Local\Temp\RtmpCW1vTW\downloaded_packages
> library("cytofkit")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘proxy’
Error: package or namespace load failed for ‘cytofkit’

**Comment by haoeric** [comment]
Could you try running codes `install.package("proxy")` then library again
