### ISSUE TITLE
Incompatibility with R 3.5

### ISSUE THREAD

**Issue by rrotkopf** [JinmiaoChenLab/cytofkit#38]
After installing cytofkit from Bioconductor, when trying to load the library, I get the message:

`package ‘cytofkit’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version.`

I've tried re-installing, but got the same error.

I would appreciate any help. Thanks!

**Comment by SamGG** [comment]
Please send the output of:
```
library(cytofkit)
packageVersion("cytofkit")
sessionInfo()
```

**Comment by rrotkopf** [comment]
``> library(cytofkit)
Loading required package: ggplot2
Loading required package: plyr
Error: package or namespace load failed for ‘cytofkit’:
 package ‘cytofkit’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version

> packageVersion("cytofkit")
[1] ‘1.10.0’

> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Hebrew_Israel.1255  LC_CTYPE=Hebrew_Israel.1255    LC_MONETARY=Hebrew_Israel.1255 LC_NUMERIC=C                  
[5] LC_TIME=Hebrew_Israel.1255    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] plyr_1.8.4    ggplot2_2.2.1

loaded via a namespace (and not attached):
 [1] colorspace_1.3-2 scales_0.5.0     compiler_3.5.0   lazyeval_0.2.1   tools_3.5.0      pillar_1.2.3     gtable_0.2.0    
 [8] tibble_1.4.2     yaml_2.1.19      Rcpp_0.12.17     grid_3.5.0       rlang_0.2.1      munsell_0.4.3

**Comment by SamGG** [comment]
Thanks. I installed mine using BiocInstaller::biocLite("cytofkit"), which leads to version 1.12.0. What's going wrong during the installation? Could you send the output?

**Comment by MattMyint** [comment]
Hi, are you facing issues with installing other packages? It seems to affect [many R packages as of R 3.5.0 ](https://community.rstudio.com/t/issues-with-packages-after-updating-to-r-3-5-0/7639/2)

[This issue](https://github.com/r-lib/devtools/issues/1772) contains a workaround solution to fixing the problematic installing. Specifically this comment 

```
library(devtools)
assignInNamespace("version_info", c(devtools:::version_info, list("3.5" = list(version_min = "3.3.0", version_max = "99.99.99", path = "bin"))), "devtools")
find_rtools() # is TRUE now
```

**Comment by rrotkopf** [comment]
Solved!
The issues were indeed common to other packages, and the solution eventually came from removing and re-installing biocLite, as described here: 
[biocLite](https://bioconductor.org/install/#troubleshoot-biocinstaller)

Thanks, everyone!

**Comment by SamGG** [comment]
Thanks for the solution! Close the issue now ;-)
