### ISSUE TITLE
ERROR: The last keyword is dropped. uneven number of tokens: 585

### ISSUE THREAD

**Issue by AbbyKimball** [JinmiaoChenLab/cytofkit#39]
I am getting the follow error message:

"The last keyword is dropped.
uneven number of tokens: 585"

What does this mean? PhenoGraph will not run due to this error message.

Thanks!

**Comment by AbbyKimball** [comment]
Update: this seems to only be an issue when I try to use normalized files, the raw files seem to work fine.

**Comment by AbbyKimball** [comment]
When trying to run unnormalized files I got a different error:

Found more than one class "file" in cache; using the first, from namespace 'RJSONIO'
Also defined by ‘BiocGenerics’
Found more than one class "file" in cache; using the first, from namespace 'RJSONIO'
Also defined by ‘BiocGenerics’
Found more than one class "file" in cache; using the first, from namespace 'RJSONIO'
Also defined by ‘BiocGenerics’
Error in read.FCS(fcsFile, transformation = FALSE) : 
  file/Users/abby/Desktop/Rivera Dataset #3/Original files downloaded from chrome/Rectum 6.fcsseems to be corrupted. 
 The actual number of cells in data section (208256) is not consistent with keyword '$TOT' (1354086)

**Comment by traumenCapote** [comment]
Did you ever figure this out? I have the same error.

**Comment by AbbyKimball** [comment]
I think I tried a couple of things and finally got it to work... the first thing I did was use Premessa to look at the channels in all of the fcs files (I have posted code for this below). I did this to make sure the channels were named the same things and were present in each file. I received some files from a collaborator that had been run on different days so the names differed slightly and a couple of channels were missing between files (hence the uneven number error). Lemme know if this solves it at all. The other thing I'd recommend is to completely quit R, restart your computer, and make sure your PhenoGraph is up to date and then try again.

```
install.packages("devtools")
source("http://bioconductor.org/biocLite.R")
biocLite("flowCore")
library(devtools)
install_github("ParkerICI/premessa")

#panel editor, must be done first, any channels that are null values must be removed, make sure all of the packages above are installed first, and the extension is just .fcs, not 'copy'
library(premessa)
paneleditor_GUI()
```
