### ISSUE TITLE
[suggestion] Allow visualization of non-clustering markers

### ISSUE THREAD

**Issue by esimonds** [JinmiaoChenLab/cytofkit#4]
Firstly, thanks for making Cytofkit. I use it a lot for t-SNE and PhenoGraph, and frequently recommend it to colleagues. I also really like how you guys keep improving it.

Lately I've run into the issue that if I have 40 parameters, I might want to cluster on only 10 of them, but I want to view the data (i.e. overlaid in t-SNE plot, or on heatmaps) for all 40 parameters. It seems that cytofkit doesn't store this data in the analysis_results$expressionData object so it's very hard to get it.

As a feature for a future version, I would like to suggest that you ask users:

1) Which parameters do you want to use for clustering/dimensionality reduction?
2) Which parameters do you want to visualize?

And preferably you would keep track of the clustering parameters somehow, perhaps with "_clust" appended to the name, or something like that.

Cheers,

Erin

**Comment by jinmiaochen** [comment]
Dear Erin,

Thanks a lot for your suggestion. We will add that feature in our next submission.

Best,
Jinmiao

**Comment by MattMyint** [comment]
Hi Erin,

Thanks for the suggestion, we've added a list into the cytofkit output that lists the markers used for clustering and dimensional reduction under `analysis_results$dimRedMarkers`.

The expression data of all markers is stored in `analysis_results$expressionData`. If you want to visualise just a subset of the data, the shiny App allows selection of specified markers.

Enjoy!

Matthew
