### ISSUE TITLE
Ask for help on install cytofkit on debian

### ISSUE THREAD

**Issue by chenziyi** [JinmiaoChenLab/cytofkit#65]
Hi sir,

I was trying to install cytofkit in my computer. At first, I install it with biocLite(). However, an error was produced as below:

Warning: S3 methods ‘as.character.tclObj’, ‘as.character.tclVar’, ‘as.double.tclObj’, ‘as.integer.tclObj’, ‘as.logical.tclObj’, ‘as.raw.tclObj’, ‘print.tclObj’, ‘[[.tclArray’, ‘[[<-.tclArray’, ‘$.tclArray’, ‘$<-.tclArray’, ‘names.tclArray’, ‘names<-.tclArray’, ‘length.tclArray’, ‘length<-.tclArray’, ‘tclObj.tclVar’, ‘tclObj<-.tclVar’, ‘tclvalue.default’, ‘tclvalue.tclObj’, ‘tclvalue.tclVar’, ‘tclvalue<-.default’, ‘tclvalue<-.tclVar’, ‘close.tkProgressBar’ were declared in NAMESPACE but not found
Error : .onLoad failed in loadNamespace() for 'tcltk', details:
  call: fun(libname, pkgname)
  error: this system not support Tcl/Tk
ERROR: lazy loading failed for package ‘cytofkit’
* removing ‘/home/chenziyi/software/R-3.5.2/library/cytofkit’

Also, when I went in to the software page, an notation says that :"this package is deprecated. It will probably be removed from Bioconductor. Please refer to the package end-of-life guidelines for more information. "

Could you please help me address this problem so I can analysis my data with your tool.

**Comment by SamGG** [comment]
Hi,
Are you using MacOS? I think tcltk is installed with R, but try to run the following commands to verify it.
```
library(tcltk)
tk_choose.dir()
tclVersion()
```

**Comment by chenziyi** [comment]
Hi,


Thanks for your reply.


I have fixed this problem by compiling my R aith the command "./configure  --with-tcl-config=/usr/lib64/tclConfig.sh --with-tk-config=/usr/lib64/tkConfig.sh".


Best.







在 2019-04-15 04:38:38，"Samuel Granjeaud" <notifications@github.com> 写道：


Hi,
Are you using MacOS? I think tcltk is installed with R, but try to run the following commands to verify it.

library(tcltk)
tk_choose.dir()
tclVersion()

**Comment by SamGG** [comment]
Thanks for your feedback. Sorry I misread the title of your issue. Could you close it if you solved it?
Best.
