### ISSUE TITLE
Parameters selection

### ISSUE THREAD

**Issue by nicoIP3278511** [JinmiaoChenLab/cytofkit#73]
Hello, 

I get the impression that even if you only select the AREA parameters, the application still uses all of the parameters contained in the FCS file (H and W) to do the analysis.
For example I select 12 parameters and I get
 Extract expression data ... 1197540 x 43 data was extracted! 

Either my 12 x3 settings (A-H-W) + FSC and SSC x3 and probably Time 
Can you tell me if this is the case? And to modify
I use R verions 3.5.0 and Cytofki 1.12.0 version

Best

**Comment by nicoIP3278511** [comment]
Hello, 

Still for this same question, I am also suprised that I have in the output files markers I excluded from my analysis. 

If anybody could help me to understand?

Best

**Comment by SamGG** [comment]
Hi,
Warning: I am not the developper nor the maintainer.

During extraction, all the markers are kept. Marker filtering occurs later. So the message is correct.

`Extract expression data ... 1197540 x 43 data was extracted!`

Before this message, there is a message listing all selected markers for the analysis. Could you check this part of the report. It begins with

`* Markers:`

If your analysis ends up with unselected markers, it should mean that cytofkit didn't understand the marker selection. Did you select the markers from the graphical user interface?

Best

**Comment by jinmiaochen** [comment]
Thanks Samuel for helping us answering the question correctly.

We apologize for not being able to answer questions in time.

Jinmiao Chen
Principal Investigator
Single-cell computational Immunology
Singapore Immunology Network (SIgN)
Agency for Science, Technology and Research (A*STAR)
8A Biomedical Grove IMMUNOS bldg, Level 3, SINGAPORE 138648
Tel: 65-64070395
Fax: 65-64642056
chen_jinmiao@immunol.a-star.edu.sg<mailto:chen_jinmiao@immunol.a-star.edu.sg>
http://www.sign.a-star.edu.sg/

**Comment by nicoIP3278511** [comment]
Thanks a lot for the reply!
 
“Before this message, there is a message listing all selected markers for the analysis” : yes I have this message.
 
“Did you select the markers from the graphical user interface?” : yes I use the interface.
 
On the web interface it is clearly specified which markers are used for the clustering, that’s why I don’t understand why I get at the end csv files (for each cluster) with these parameters I just excluded.
Is it normal?
Does it mean that they are not used for the clustering but still “analyzed” for each cell?
 
Best

**Comment by SamGG** [comment]
Hi Nico,

> Does it mean that they are not used for the clustering but still “analyzed” for each cell?

Exactly, you got it. Following the stream of Tibshirani, Robinson and some others, phenotypic markers are used to cluster the cells. Their histogram shows usually a nice bimodal shape. These are the ones you select in Cytofkit. Functional markers are the markers for which we look for a mean shift typically. So functional are typically not selected for clustering but are reported for each cluster in order to assess a "statistical" mean shift.

Best.

**Comment by nicoIP3278511** [comment]
Thanks a lot! Ok I understand now.

**Comment by SamGG** [comment]
Perfect.
a) If you are France, may be we will meet at French Cyto https://www.alphavisa.com/afc/2019/
b) Please, could you close all the issues you opened if you feel they do no longer hold.
Best.
