### ISSUE TITLE
[suggestion] Include cluster ID (integer) in analyzedFCS output

### ISSUE THREAD

**Issue by esimonds** [JinmiaoChenLab/cytofkit#8]
When doing PhenoGraph clustering in Cytofkit, the FCS file output to the "analyzedFCS" folder contains some useful new parameters. For example:

> ...
> $P44            tsne_1    <NA>       74  0.00000000       75
> $P45            tsne_2    <NA>       80  0.00000000       81
> $P46 Rphenograph_cor_1    <NA>     3178 -0.08243132     3178
> $P47 Rphenograph_cor_2    <NA>     3178 -0.08243132     3178
> 363 keywords are stored in the 'description' slot

...however, it does not contain the cluster IDs. It would be very handy if these were added as the final column of the FCS file, as integers corresponding to the cluster IDs in the interactive Cytofkit display.

**Comment by jinmiaochen** [comment]
Dear Erin,

Thanks a lot for your feedback. We will add the cluster ID as integers to FCS in our next version.

Best,
Jinmiao

**Comment by MattMyint** [comment]
Hi Erin!

Its taken a while, but we've incorporated your suggestion into cytofkit! You can try it on the devel branch (i.e. this github repo)

Let me know if there's any issues!

Regards
Matthew

**Comment by esimonds** [comment]
Thanks, I'm excited to try it!
