### ISSUE TITLE
New computer, new error message

### ISSUE THREAD

**Issue by AbbyKimball** [JinmiaoChenLab/cytofkit#9]
I recently got the newest mac and ever since this I have had an issue opening the heat map in shiny app, I get the error: "cannot open file 'cytofkit_shinyAPP_marker_heatmap_plot.pdf" I have tried loading the data into the shiny app on other computers, and it has worked. This has also occured with three different data sets. Thanks!

**Comment by MattMyint** [comment]
Hi,

Thanks for spotting that!

Just to get a clearer picture, does your heatmap fail to render on the shiny app? Or does this occur when trying to save the heatmap to PDF?

Regards,
Matthew

**Comment by AbbyKimball** [comment]
Hi! The heatmap fails to render on the app... thanks :)

**Comment by MattMyint** [comment]
Okay, we'll be pushing out updates with fixes for various issues soon. Thanks for the feedback!

**Comment by MattMyint** [comment]
Hi!

We've updated the devel version of cytofkit with some interim fixes, you can get it here using `devtools::install_github("JinmiaoChenLab/cytofkit")` or using the devel version of bioconductor.

Let me know if you still face issues!

Thanks

**Comment by MattMyint** [comment]
Closing the issue. If the problem persists feel free to reopen!
