### ISSUE TITLE
Read.flow.Set error

### ISSUE THREAD

**Issue by nayaracleite** [JinmiaoChenLab/cytofkit#93]
Hello, 

I'm getting this error when I try to load the .FCS files:

_

> Warning in readFCSdata(con, offsets, txt, transformation, which.lines, scale,  :
>   Some data values of 'Er167Di' channel exceed its $PnR value 12000 and will be truncated!
>  To avoid truncation, either fix $PnR before generating FCS or set 'truncate_max_range = FALSE'

_

Do you have any idea how to fix it? 

Thank you
Nayara

**Comment by SamGG** [comment]
Hi,
You might find more support on cytofkit2. Nevertheless cytofkit2 didn't correct this error.

To solve it you have to change the code at https://github.com/JinmiaoChenLab/cytofkit/blob/3d134085453231403a3cf327e981b419f966295c/R/cytof_preProcess.R#L131 and https://github.com/JinmiaoChenLab/cytofkit/blob/3d134085453231403a3cf327e981b419f966295c/R/cytof_preProcess.R#L133 and replace  ```FALSE)``` by ```FALSE, truncate_max_range = FALSE)```

Alternatively, you could try my own fork in which I already corrected this problem.
https://github.com/i-cyto/cytofkitlab

HTH,
Samuel

**Comment by nayaracleite** [comment]
Awesome, it worked! Thank you.
